CREATE DATABASE `db_auth` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `db_info` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `db_log` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
